---
- name: Cria serviço myapp nas apps
  hosts: apps
  become: yes
  tasks:
    - name: Cria arquivo de serviço systemd
      copy:
        dest: /etc/systemd/system/myapp.service
        content: |
          [Unit]
          Description=MyApp Custom Service
          After=network.target

          [Service]
          Type=simple
          ExecStart=/opt/myapp/myapp
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Cria diretório /opt/myapp/ com permissões de execução e leitura para todos
      file:
        path: /opt/myapp
        mode: '0755'
        state: directory

    - name: Ativa e inicia o serviço
      systemd:
        name: myapp
        enabled: yes
        state: started
