# .github/workflows/ci-cd.yml

name: Go API CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Build
      run: go build -v -o myapp -ldflags="-s -w" ./
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-binary
        path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build # Faz o deploy depender do build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: myapp-binary
        path: ./
    
    - name: Set executable permissions
      run: chmod +x myapp
    
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key myapp $SERVER_USER@$SERVER_HOST:$SERVER_PATH
        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "cd $SERVER_PATH && nohup ./myapp > app.log 2>&1 &"
