
name: Go API CI/CD Pipeline
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - configs/**
      - controllers/**
      - models/**
      - routes/**
  pull_request:
    branches:
      - main
    paths:
      - configs/**
      - controllers/**
      - models/**
      - routes/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v -o myapp -ldflags="-s -w" ./
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-binary
          path: myapp
  
  deploy:
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        server:
          - 1
          - 2
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-binary
          path: ./
      - name: Set executable permissions
        run: chmod +x myapp
      - name: Deploy to server-${{ matrix.server }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ matrix.server == 1 && secrets.SERVER_HOST_1 || secrets.SERVER_HOST_2 }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}

        run: |
        
          # Parar o serviço antes de copiar o binário
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo systemctl stop myapp.service"
          
          # # Remover o binário antigo ou ajustar permissões
          # ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo rm -f $SERVER_PATH/myapp || sudo chmod 664 $SERVER_PATH/myapp"
          
          # # Copiar o novo binário
          # scp -o StrictHostKeyChecking=no -i private_key myapp $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          
          # # Ajustar permissões e reiniciar o serviço
          # ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo chmod +x $SERVER_PATH/myapp && sudo systemctl start myapp.service"
          
          # rm private_key

              

